version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MODEL_PATH=TheBloke/Llama-2-7B-Chat-GGUF
      - VECTOR_STORE_PATH=/app/data/vector_store
      - DEVICE=cpu
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  vector_store:
